high-availability.html.md.erb

[#86469190]
Signed-off-by: Greg Ziebold <gziebold@pivotal.io>

Update loggregator to doppler nomenclature.

---

high-availability.html.md.erb

This pull request will resolve problem stated in https://www.pivotaltracker.com/story/show/86958204

Adding Etcd information on Single-node processes

---

glossary.html.md.erb

I suggest adding "Managed Services" and "UAA" to the glossary.

Mention "Managed Services" and "UAA" in the glossary.

---

architecture/index.html.md.erb

we should leverage the variables we have :)

replace services with link

---

high-availability.html.md.erb

Update HA documentation for Diego OSS VMs

---

_oss_roles_table.html.md.erb
architecture/router.html.md.erb
glossary.html.md.erb
high-availability.html.md.erb
how-applications-are-staged.html.md.erb
security.html.md.erb

Spaces, it is aligned to view code with any editor, including the web page view (such as in the GitHub code). When use tabs, the view on the page is chaos, and it is terrible to mix tabs and spaces.

Replace the tab with spaces

---

architecture/warden.html.md.erb

Explained the CPU shares concept used in Cloud Foundry with more details and example.

Improving the CPU shares concept documentation

---

architecture/warden.html.md.erb

Refining the submitted documentation about CPU shares from yesterday.

Reefined CPU shares documentation

---

_oss_scale_table.html.md.erb

** DO NOT MERGE UNTIL https://github.com/cloudfoundry/cf-release/pull/1134 IS MERGED **
[#136621261]

Include HA info for cc clock + workers

---

_oss_roles_table.html.md.erb

Space auditors are able to list and view spaces which they audit

Fix permissions w.r.t. viewing spaces

---

roles.html.md.erb

Tracker story: https://www.pivotaltracker.com/story/show/134374455
Associated PR: https://github.com/cloudfoundry/docs-book-cloudfoundry/pull/64
Signed-off-by: Greg Cobb <gcobb@pivotal.io>

Add global auditor to roles page

---

architecture/index.html.md.erb

Related to https://github.com/cloudfoundry/diego-release/issues/344.

Clarify activity on Diego cell

---

http-routing.html.md.erb

We are making some doc changes to include the new features to sanitize HTTP headers and securing route services.

Doc changes for HTTP Headers

---

_oss_roles_table.html.md.erb

Hello from CAPI!
Please do not merge until our PM, @zrob has had a chance to review these changes.
Finishes [#158923727](https://www.pivotaltracker.com/story/show/158923727)
Thanks!
/cc @mkenyon

Add permission for sharing private domains

---

http-routing.html.md.erb

Please don't merge until our PMs have accepted [this story](https://www.pivotaltracker.com/story/show/157521684).
[#157521684]
Thanks,
@jeffpak and @utako, CF Routing Team

add case on gorouter retry behavior when backend crashes

---

architecture/uaa.html.md.erb

#router-scopes -> #routing-scopes.

Fix anchor link.

---

http-routing.html.md.erb

* Add "Router Balancing Algorithm" section to HTTP Routing Docs
* Rewrite "Round-Robin Load Balancing" section
* Add description of "Least Connection Load Balancing"
[#167717621]

Add routing algo section in HTTP routing docs

---

asg.html.md.erb

Clarify that the relationship for combined ASGs is the disjunction of all applicable ASGs.

Improve description of how ASGs combine

---

_oss_roles_table.html.md.erb
roles.html.md.erb

[#168292911](https://www.pivotaltracker.com/story/show/168292911)

Add service brokers (global and space-scoped) to role page.

---

http-routing.html.md.erb

Clarify information about error codes and headers when requests fail. 
[#171304381](https://www.pivotaltracker.com/story/show/171304381)

Update information about Surgical Routing

---

http-routing.html.md.erb

- a continuation of this PR: https://github.com/cloudfoundry/docs-cloudfoundry-concepts/pull/134
- just trying to make sure things are clear :)

update surgical routing docs

---

architecture/router.html.md.erb

* add section on x-cf-routererror values
* add x-cf-routererror to access log
[#173046359](https://www.pivotaltracker.com/story/show/173046359)
Co-authored-by: Clay Kauzlaric <ckauzlaric@vmware.com>

update access log information

---

_oss_roles_table.html.md.erb

Let me know if you have any questions or if I should make any changes. 
Thanks!
🐱

add c2c info to roles table

---

cf-routing-architecture.html.md.erb

You have not been able to since 2.4

You can no longer disable TLS route verification

---

http-routing.html.md.erb

[#175134947](https://www.pivotaltracker.com/n/projects/2245598/stories/175134947)

Update docs to reflect new VCAP_ID expiry

---

roles.html.md.erb

We are adding a new role to cloud foundry which spawned from this github project: https://github.com/orgs/cloudfoundry/projects/6
This is the first of several PRs we are going to make for this new role. If you have any suggestion or find anything confusing please let us know.

Add section for space supporter role

---

_oss_roles_table.html.md.erb
roles.html.md.erb

* add brief description
* add to roles table
Currently available with a code flag in cc, soon to be available
without a feature flag.
Co-authored-by: Matthew Kocher <mkocher@pivotal.io>
Co-authored-by: Mona Mohebbi <mmohebbi@pivotal.io>

Add space supporter docs

---

http-routing.html.md.erb

Authored-by: Ramkumar Vengadakrishnan <ramkumarv@vmware.com>

Don't link to Admin or Operating Guides in TAS offline docs

---

http-routing.html.md.erb

Align documentation with gorouter [PR-335](https://github.com/cloudfoundry/gorouter/pull/335)

Gorouter maxAttempts configurable for endpoints and route-services

---

http-routing.html.md.erb

Adding section to HTTP Routing about W3C tracing.

Add section describing W3C headers

---

asg.html.md.erb

Adding specific notes for restarting Dynamic ASGs.
For docs team: Is there a branch we should commit to to propogate changes to 2.11 and 2.13? Thank you very much.

Specify `cf restart` for dynamic ASGs to take effect

---

asg.html.md.erb

Specify `cf restart` command for ASGs to take effect.
Also made "Staging and running ASGs" an H2 to fix  `BadHeadingLevelError`.

Specify cf restart command for ASGs to take effect.

---

http-routing.html.md.erb

- Adds documentation related to the AZ-local routing feature introduced in [routing-release 0.288.0](https://github.com/cloudfoundry/routing-release/releases/tag/v0.288.0)
See this Github issue for more information:
- https://github.com/cloudfoundry/routing-release/issues/356
[#186117321](https://www.pivotaltracker.com/story/show/186117321)

Adds docs for router AZ preference feature

---

asg.html.md.erb

This change is valid for all versions of CF and TAS.
❓ Can whoever merges this make sure it makes it on all supported versions of the docs please?

add warning about windows apps and ASG limits - master

---

container-security.html.md.erb

Hi @anita-flegg , 
I added even more information about the cpu shares algorithm here. I even made sure it looks good when running it locally.
❓ Can you please cherry-pick these changes to all branches for TAS + C?
✨ Thank you!

Add more information about magic numbers in cpu shares algorithm
