cloudfoundry/docs-cloudfoundry-concepts

- stacks.html.md
The lucid64 stack is no longer available for installation.
> Remove references to lucid64

- _oss_scale_table.html.md.erb
- only one is needed b/c it does not do anything mission critical
> the clock is no longer ha

- asg.html.md.erb
The "Understanding Application Security Groups" section of the docs has a note that states:
> To apply a staging ASG to apps within a space, you must use the CC API. The cf CLI `cf bind-security-group` command supports space-scoped running ASGs, but not space-scoped staging ASGs.
The CF CLI installed via brew (`cf version 6.26.0+9c9a261fd.2017-04-06`) contains a `bind-staging-security-group` command, so this change just reflects this in the docs.
> Add bing-staging-security-group support

- index.html.md.erb
...since these are community docs that should apply to any downstream deployment, not just PCF.
> Replace PCF references with cf-release

- asg.html.md.erb
cf CLI 6.4 was released almost 3 years ago. This note has become clutter.
> removed minimum requirement of old cf CLI

- http-routing.html.md.erb
Documenting a new feature in the CF HTTP Router.
[Story #149933885](https://www.pivotaltracker.com/story/show/149933885)
> HTTP Routing: forward client certificate to applications

- architecture/garden.html.md.erb
- container-security.html.md.erb
Add information about Grootfs to the garden architecture page.
Update container security with how Grootfs handles the filesystem
creation and its specific security implementation details.
(Also updates some links to the garden-runc-release repository, which is no longer in the cloudfoundry-incubator organization)
[#150266114 #150265783]
> Add reference to grootfs

- _oss_roles_table.html.md.erb
- _suspended_org_roles_table.html.md.erb
- roles.html.md.erb
In order for my end-users in our regulated environment to have confidence that they are managing access to their orgs appropriately according to their access control requirements, they need to understand CF org user management in depth, including hidden/implied roles.
This is a proposal for documenting Org User status, following up on my comment at https://github.com/cloudfoundry/cli/issues/781#issuecomment-311832690 and [this discussion in #cf-docs in the Cloud Foundry Slack](https://cloudfoundry.slack.com/archives/C03B0T0D5/p1498687757249593). I figure an illustration of what might be helpful to us can be helpful. :)
This is a best guess at what the documentation should look like - I haven't verified all of the checkboxes here, and I haven't tried running this locally to check for …
> Add Org User status to roles description and table

- roles.html.md.erb
Users commonly ask what scopes are needed to hit endpoints. This will help clarify how scopes/ user roles interact with eachother.
> Add docs for cloud_controller.read and .write

- asg.html.md.erb
According to https://www.iana.org/assignments/icmp-parameters/icmp-parameters.xhtml, the pair of type 0 and code 1 is invalid.
> Use valid ICMP type/code pair in the ASG example

- architecture/warden.html.md.erb
As of garden-runc-release v1.9.4 the container's cgroups are available in the container ([see this discussion](https://github.com/cloudfoundry/java-buildpack-memory-calculator/issues/11#issuecomment-350745306)).
The old path does not exist anymore and is therefore removed from the documentation.
> Update cgroup information

- _oss_roles_table.html.md.erb
This change fixes the permissions table to show that OrgManager has the
ability to 'View the status, number of instances, service bindings, and
resource use of applications', and OrgBillingManager does not.
We've verified on the latest Cloud Foundry version (cf deployment
v1.14.0) that this is correct.
Thanks,
Niki and @jenspinney
> Fix incorrectly documented permissions

- architecture/warden.html.md.erb
- container-security.html.md.erb
This moves the documentation about CPU isolation from the outdated warden architecture page to the dedicated container security documentation.
Since cgroups are still used in garden (Diego) and this document is still up-to-date it only makes sense to move this chapter to a site where people actually expect it to be. A link was introduced to point to the new page.
Outdated details about the non-existing DEA architecture were removed.
> Move CPU Isolation docs to Container Security

- roles.html.md.erb
An org can have zero spaces, so it's not correct to say that an org contains at least one space.  We have maintained the emphasis that an org can contain many spaces, but without being factually inaccurate.
Paired with @blgm
> Update statement about spaces within an org

- architecture/uaa.html.md.erb
Fix incorrect instructions for obtaining OAuth tokens using uaac. Also update command outputs that have changed significantly since these instructions were written for UAA 1.8.3 in 2014.
> Update uaac token commands

- _oss_roles_table.html.md.erb
Implements Tracker story: [#157755345][pt]
Story details say to wait to merge until CAPI PM @zrob can verifies the change.
[pt]: https://www.pivotaltracker.com/story/show/157755345
> Correction that org managers can rename orgs

- http-routing.html.md.erb
As discussed in https://github.com/cloudfoundry/routing-release/issues/110, the current docs don't match the actual behaviour of gorouter. It doesn't perform the promotion for these headers any more, and instead passes them through unmodified.
> Update Zipkin header docs to reflect actual behaviour

- container-security.html.md.erb
Hello,
it was very hard to find that is possible to limit bandwidth on application container level, therefore I propose to include this parameter on the documentation. 
Mention the configuration parameters present here https://github.com/cloudfoundry/silk-release/blob/92398d2fa7635479cec83b9d7046e5071c132806/jobs/silk-cni/spec#L38-L44
Best,
Michael
> Mention bandwidth rate limits for app containers

- http-routing.html.md.erb
Approved by networking folks here:
https://pivotal.slack.com/archives/CFKJZ9B3J/p1559149057090300
>  X-Forwarded-Proto header can have multiple values

- http-routing.html.md.erb
Approved by networking folks here:
https://pivotal.slack.com/archives/CFKJZ9B3J/p1559149057090300
> X-Forwarded-Proto header can have multiple values

- architecture/uaa.html.md.erb
Because check_token is deprecated
[#168552270]
@cloudfoundry/cf-uaa
> Update `/check_token` to `/introspect`

- architecture/router.html.md.erb
- we added a new field on the access logs: gorouter_time
- we wanted to be clear about the differences between response time and gorouter time, so we added definitions
[#170285659](https://www.pivotaltracker.com/story/show/170285659)
> add gorouter time to gorouter access log docs

- architecture/router.html.md.erb
- cf-routing-architecture.html.md.erb
- http-routing.html.md.erb
- understand-cf-networking.html.md.erb
Replaces:
- Routing
- Container-to-Container Networking
- CF Networking
[#174581818](https://www.pivotaltracker.com/story/show/174581818)
This change should also be backported all the way back to TAS `2.7` 
- https://github.com/cloudfoundry/docs-dev-guide/pull/410
- https://github.com/cloudfoundry/docs-cf-admin/pull/189
- https://github.com/cloudfoundry/docs-cloudfoundry-concepts/pull/146
- https://github.com/pivotal-cf/docs-operating-pas/pull/38
- https://github.com/pivotal-cf/docs-ops-manager/pull/93
- https://github.com/pivotal-cf/docs-pcf-security/pull/116
>  Update owner: CF for VMs Networking

- roles.html.md.erb
Hey docs friends!
In v3 org user is no longer auto assigned when an org manager grants any org or space role.
This change came from the following github issue in CCNG: https://github.com/cloudfoundry/cloud_controller_ng/issues/2130
Thanks,
Jenna and @sethboyles
> Update org user role for v3/v2

- http-routing.html.md.erb
Clarify on HTTP header size, especially practical limits in a real deployment. Also corrected the error of gorouter keep-alive backend connection limits.
> Clarify on http routing

- asg.html.md.erb
Since cf cli v7, the usage of `cf bind-security-group` has been changed as below - i.e., we need to specify SPACE with `--space`
- cf bind-security-group SECURITY_GROUP ORG [--lifecycle (running | staging)] [--space SPACE]
Based on this change, the ASG docs for TAS 2.11 should be change because it's requred to use cf cli v7.
> SPACE configuration for cf bind-security-group

- understand-cf-networking.html.md.erb
There's a major new feature in the platform, an [automatic TLS-secured port](https://github.com/cloudfoundry/diego-release/issues/587#issuecomment-999142420) for apps to receive container-to-container network connections. This is a big deal, but there's no documentation about it AFAIK beyond that GitHub comment.
This PR edits [the existing "Securing Container-to-Container Traffic" content](https://docs.cloudfoundry.org/concepts/understand-cf-networking.html#securing-traffic) to describe this feature.
It also removes a vendor-specific reference that does not apply to the community-supported version of Cloud Foundry.
> Document new automatic TLS option for C2C networking

- _oss_scale_table.html.md.erb
* Log Cache has been split out to its own instance group:
https://github.com/cloudfoundry/cf-deployment/releases/tag/v18.0.0
* Remove stale reference to etcd
> Add log cache instance group

- diego/diego-architecture.html.md.erb
There is a recent customer requesting clarification on how many diego cells are recommended. This updated documentation is created to have a starting point for discussions related to how many diego cells can be on a single foundation.
> Max 250 diego cells

- _oss_roles_table.html.md.erb
Non-admins have the ability to bind and unbind ASGs for the orgs and spaces that they can manage. This change adds additional rows in the table to make that explicit.
> add non-admin ASG commands to role permissions table

- understand-cf-networking.html.md.erb
It is not an option you enable. Platform always provides this to you.
Reword the C2C networking section to reflect that and specify in what
case you might want to use your own TLS termination.
Signed-off-by: Geoff Franks <gfranks@vmware.com>
> Change wording for C2C TLS feature

- _oss_roles_table.html.md.erb
- _suspended_org_roles_table.html.md.erb
- roles.html.md.erb
- With the addition of log rate limiting we decided to no longer enumerate all of the resource types that can be allocated.
- Also mention log rate as a resource that can be constrained.
@ctlong
> Add log rate limiting docs

- _oss_healthchecker_documentation.md.erb
- architecture/garden.html.md.erb
- cf-routing-architecture.html.md.erb
- diego/diego-architecture.html.md.erb
Signed-off-by: Marc Paquette <mpaquette@vmware.com>
The healthchecker-release has now been externalized to it's own release.  This documentation has been updated to outline how healthchecker's behavior is different than the standard monit health check.
> Add Healthchecker documentation

- security.html.md.erb
This client is needed to access the CF API programatically in PaaS foundations where users don't have the option to create own UAA clients.
See also https://github.com/cloudfoundry/cli/discussions/2379
> Document UAA client "cf"

- diego/diego-architecture.html.md.erb
Update Healthcheck binary description. Monitor action in LRP is deprecated in favor of CheckDefinition since 2017.
> Update Healthcheck binary description

- asg.html.md.erb
* Specify cf restart command
* Make `Staging and running ASGs` an H2 due to markdown error
* Change placement of "To apply an ASG, you must first bind it to an ASG set" for clarity
> specify cf restart command for applying asgs

- _oss_healthchecker_documentation.md.erb
- architecture/garden.html.md.erb
Updating the documentation to reflect the most up to date information for garden-runc releases.
We removed the healthchecker in [Garden-runc-release v1.43.0](https://github.com/cloudfoundry/garden-runc-release/releases/tag/v1.43.0)
> Update documentation to reflect the changes within Garden-runc-release v1.43.0

- container-security.html.md.erb
In this PR I documented two different CPU shares algorithms...
1. Using open source CF, operators have the choice between algorithms. They can also configure a handful of properties that  affect algorithm 1. 
2. All supported versions of TAS automatically use algorithm 2. TAS docs don't even need to explain the first algorithm.
😅 I did my best to document this. Please let me know if there is anything I can improve. If you have any feedback please reach me on slack @ameowlia . I will respond there much quicker.
✨ TY!
> explain both cpu shares algorithms

- asg.html.md.erb
All new content is behind a if block and shown in OSS docs only. Once this feature is in TAS I will update the TAS docs.
> ASG destinations can now be a list in OS CF

- http-routing.html.md.erb
We found out that so-called surgical requests, where X-Cf-App-Instance is used to call a specific instance, are not supported in the route service scenario. The header is always dropped even before sending the first request to the route service, and the header is not considered when making the actual call to the target application.
This behavior has been implemented in 2016, see this [Git commit](https://github.com/cloudfoundry/gorouter/commit/c5d74c01d117952947a2a64880d4a8179154082c).
This is the related story: https://pivotaltracker.com/n/projects/1358110/stories/129122189
> Add note about X-Cf-App-Instance incompatibility with route services

- architecture/cloud-controller.html.md.erb
- cc-blobstore.html.md.erb
https://docs.cloudfoundry.org/concepts/architecture/cloud-controller.html and https://docs.cloudfoundry.org/concepts/cc-blobstore.html currently both have complementary blobstore sections, so I thought it best to combine them into a single page.  I also added a warning against pointing two foundations at the same blobstore.
> Consolidate blobstore sections

- understand-cf-networking.html.md.erb
Draft because this work is not merged in yet. Longer description of this work is here: https://github.com/cloudfoundry/silk-release/pull/148
This change should only be for....
* open source
* TPCF 10.2 (or whatever version is next)
This change is NOT for...
* TPCF 10
* TAS 6
* TAS 4
> default overlay network is now an array of CIDRs
